export { starCipher } from "./star";
export { triangleCipher } from "./triangle";
export { xCipher } from "./x";
export { morseCipher } from "./morse";
export { diamondCipher } from "./diamond";
export { compassCipher } from "./compass";
export { dominosCipher } from "./dominos";
export { semaphoreCipher } from "./semaphore";
export { squareCipher } from "./square";